Make a stub web-page too

diff --git a/bin/update-sites b/bin/update-sites
--- a/bin/update-sites
+++ b/bin/update-sites
@@ -9,10 +9,13 @@ readonly WellKnownTop='.well-known/openpgpkey'
 note() { printf >&2 '%s: %s\n' "$ProgramName" "$*"; }
 die() { note "$@"; exit 1; }
 
+python='python'
+if which python3 >/dev/null 2>&1; then python='python3'; fi
+
 which pcregrep >/dev/null 2>&1    || die "missing command: pcregrep"
 test -f "$TopDir/config/keys"     || die "missing config/keys"
 test -f "$TopDir/config/domains"  || die "missing config/domains"
-python -c 'import pdpzbase32'     || die "missing python pdpzbase32 (from .personal)"
+$python -c 'import pdpzbase32'    || die "missing python pdpzbase32 (from .personal)"
 
 test -d "$TopDir/sites"           || die "missing sites dir"
 rm -rf "$TopDir/sites"
@@ -27,6 +30,11 @@ for domain in "${Domains[@]}"; do
 		mkdir -pv "$d/hu"
 		touch "$d/policy"
 	done
+	cat >"$TopDir/sites/$domain/index.html" <<'EOHTML'
+<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
+<title>No web-pages</title></head><body>No content on this site should be a web-page.<br>
+(Except, by reduction, this one.)</body></html>
+EOHTML
 done
 
 for key in "${Keys[@]}"; do
@@ -47,7 +55,7 @@ for key in "${Keys[@]}"; do
 		# Filter out domains which we're not handling here
 		test -d "$TopDir/sites/$domain" || continue
 
-		encoded_lhs="$(python -c '
+		encoded_lhs="$($python -c '
 import hashlib, sys, pdpzbase32
 print(pdpzbase32.encode(hashlib.sha1(sys.argv[1].lower().encode("ASCII")).digest()).decode("ASCII"))' "$lhs")"
 		note "[$key] $email -> $domain :: $lhs :: $encoded_lhs"
